services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-billing
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./data:/metabase-data
    restart: unless-stopped
    networks:
      - metabase-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ../dist:/app/dist
    depends_on:
      - metabase
    restart: unless-stopped
    networks:
      - metabase-network
    extra_hosts:
      - "billing.local:host-gateway"
      - "host.docker.internal:host-gateway"

networks:
  metabase-network:
    driver: bridge